services:
  server:
    build: .
    ports:
      - "8000:5000"
  pgDB:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    ports:
      - '5429:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geoexample
volumes:
  db_data: